apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-proxy-server
  labels:
    app: polygon-proxy-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polygon-proxy-server
  template:
    metadata:
      labels:
        app: polygon-proxy-server
    spec:
      containers:
      - name: polygon-proxy-server
        image: us-central1-docker.pkg.dev/consensus-447101/polygon-proxy/polygon-proxy-server:latest
        ports:
        - containerPort: 8090
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
